# Generated by Django 4.2.7 on 2026-07-02 05:53

from django.db import migrations, models
import django.db.models.deletion
import loyalty_backend.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlOfDeleyas",
            fields=[
                (
                    "date",
                    models.CharField(
                        help_text="Date in YYYY-MM-DD format",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Контроль опозданий",
                "verbose_name_plural": "Контроль опозданий",
                "db_table": "control_of_delays",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grafic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "График",
                "verbose_name_plural": "График сотрудников",
                "db_table": "grafic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.BigIntegerField(help_text="Telegram or MAX user ID"),
                ),
                (
                    "username",
                    models.CharField(help_text="Employee full name", max_length=100),
                ),
                (
                    "log_prefix",
                    models.CharField(
                        help_text="Role: Сотрудник/Сменщик/Помощник", max_length=50
                    ),
                ),
                (
                    "point",
                    models.CharField(
                        blank=True,
                        help_text="Cashier point name",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "time_send",
                    models.CharField(help_text="Time in HH:MM format", max_length=10),
                ),
                (
                    "date",
                    models.CharField(
                        help_text="Date in YYYY-MM-DD format", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Геолокация",
                "verbose_name_plural": "Геолокации",
                "db_table": "locations",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cashier",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID кассы"
                    ),
                ),
                (
                    "adress",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Полный адрес"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=100, verbose_name="Активирование кассы"
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "short_name_point",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Краткое название точки",
                    ),
                ),
                ("start_work", models.TimeField(verbose_name="Во сколько открывается")),
                ("end_work", models.TimeField(verbose_name="Во сколько закрывается")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (e.g., 55.7558)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (e.g., 37.6173)",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Кассы",
                "verbose_name_plural": "Кассы",
                "db_table": "cashier",
            },
        ),
        migrations.CreateModel(
            name="CategoryMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("used_in_menu", models.BooleanField()),
            ],
            options={
                "verbose_name": "Категории меню",
                "verbose_name_plural": "Категории меню",
                "db_table": "category_menu",
            },
        ),
        migrations.CreateModel(
            name="CategoryProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                ("description", models.CharField(verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "Категории продуктов",
                "verbose_name_plural": "Категории продуктов",
                "db_table": "category_products",
            },
        ),
        migrations.CreateModel(
            name="CheckList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(max_length=100, verbose_name="Наименование"),
                ),
                ("count", models.IntegerField(verbose_name="Количество")),
                ("unit", models.TextField(verbose_name="Единицы измерения")),
            ],
            options={
                "verbose_name": "Чек лист",
                "verbose_name_plural": "Чек лист",
                "db_table": "check_list",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tg_id",
                    models.BigIntegerField(
                        default=loyalty_backend.models.generate_tg_id, unique=True
                    ),
                ),
                ("drink", models.CharField(max_length=100)),
                (
                    "syrup",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vanilla", "Ваниль"),
                            ("caramel", "Карамель"),
                            ("chocolate", "Шоколад"),
                            ("salt_caramel", "Соленая карамель"),
                            ("strawberry", "Клубника"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("max_id", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "size",
                    models.IntegerField(default=250, verbose_name="Объем напитка"),
                ),
                (
                    "url",
                    models.ImageField(
                        upload_to="products/", verbose_name="URL картинки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Напитки по купону",
                "verbose_name_plural": "Напитки по купону",
                "db_table": "loyalty_backend_drink",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID сотрудника"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "full_name",
                    models.CharField(max_length=100, unique=True, verbose_name="ФИО"),
                ),
                ("birthday", models.DateField(verbose_name="День рождения")),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("boss", "Босс"),
                            ("admin", "Админ"),
                            ("SMM", "SMM"),
                            ("employee", "Сотрудник"),
                        ],
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(max_length=100, verbose_name="Телеграм ссылка"),
                ),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Номер телефона"),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала работы")),
                (
                    "experience",
                    models.CharField(max_length=100, verbose_name="Опыт был/не было"),
                ),
                (
                    "type_salary",
                    models.CharField(max_length=100, verbose_name="Тип ставки"),
                ),
                ("rate", models.BigIntegerField(verbose_name="Час ставка")),
                ("percent", models.BigIntegerField(verbose_name="Процент")),
                (
                    "active_status",
                    models.CharField(
                        max_length=20, verbose_name="Активирование пользователя"
                    ),
                ),
                ("max_user_id", models.BigIntegerField(default=0)),
                ("avatar", models.TextField()),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название статьи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья расходов",
                "verbose_name_plural": "Статьи расходов",
                "db_table": "expense_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LotteryParticipant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tg_id", models.BigIntegerField(unique=True)),
                ("lottery_number", models.CharField(max_length=20, unique=True)),
                ("is_winner", models.BooleanField(default=False)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Участник лотереи",
                "verbose_name_plural": "Участники лотереи",
                "db_table": "lottery_participants",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "how_find",
                    models.CharField(
                        choices=[
                            ("mai", "МЭИ"),
                            ("mtusy", "МТУСИ"),
                            ("yandex", "Яндекс карты"),
                            ("friend", "Посоветовали друзья"),
                            ("street", "Проходил мимо"),
                            ("social media", "Соцсети"),
                        ],
                        max_length=50,
                    ),
                ),
                ("birthday", models.DateField()),
                ("bonuses", models.BigIntegerField(default=0)),
                ("university_percent", models.IntegerField(default=0)),
                ("max_id", models.BigIntegerField(default=0)),
                ("avatar", models.TextField()),
            ],
            options={
                "verbose_name": "Карты лояльности",
                "verbose_name_plural": "Карты лояльности",
                "db_table": "loyalty_card",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name=""
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=100, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "category",
                    models.TextField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100, null=True, verbose_name="описание напитка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "db_table": "menu",
            },
        ),
        migrations.CreateModel(
            name="Milk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Нименование"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Цена")),
                ("unit", models.IntegerField(verbose_name="Количество в 1 позиции")),
            ],
            options={
                "verbose_name": "Молоко",
                "verbose_name_plural": "Молоко",
                "db_table": "milk",
            },
        ),
        migrations.CreateModel(
            name="MilkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("confirmed", "confirmed"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                            ("problem", "problem"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        db_column="cashier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_orders",
                        to="loyalty_backend.cashier",
                        to_field="short_name_point",
                        verbose_name="Точка",
                    ),
                ),
                (
                    "cashier_address",
                    models.ForeignKey(
                        db_column="cashier_address",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_orders_address",
                        to="loyalty_backend.cashier",
                        to_field="adress",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ молока",
                "verbose_name_plural": "Заказы молока",
                "db_table": "milk_order",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="ID товара"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=100, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "category",
                    models.TextField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "url",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Фото",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "barcode",
                    models.BigIntegerField(verbose_name="Штрихкод (если есть)"),
                ),
            ],
            options={
                "verbose_name": "Товары",
                "verbose_name_plural": "Товары",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Syrup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название сиропа"),
                ),
                (
                    "url",
                    models.ImageField(upload_to="syrup/", verbose_name="URL картинки"),
                ),
            ],
            options={
                "verbose_name": "Сиропы",
                "verbose_name_plural": "Сиропы",
                "db_table": "loyalty_backend_syrup",
            },
        ),
        migrations.CreateModel(
            name="TimeScanQR",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("loyalty_card", models.BigIntegerField()),
                ("shift_id", models.BigIntegerField()),
                ("cashier_id", models.BigIntegerField()),
                ("scan_time", models.DateTimeField()),
                ("bonus_used", models.IntegerField(default=0)),
                ("used_at", models.BooleanField(default=False)),
                ("comment_loyalty_card", models.CharField()),
                ("is_own_cup", models.IntegerField()),
            ],
            options={
                "db_table": "time_scan_qr",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_shift", models.DateField()),
                ("active_status", models.CharField(max_length=100)),
                (
                    "cashier_id",
                    models.ForeignKey(
                        db_column="cashier_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.cashier",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смены",
                "verbose_name_plural": "Смены",
                "db_table": "shift",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=100)),
                ("date_operation", models.DateTimeField(blank=True, null=True)),
                ("amount", models.BigIntegerField()),
                ("payment_method", models.CharField(max_length=100)),
                ("bonus_add", models.BigIntegerField()),
                ("bonus_remove", models.BigIntegerField()),
                (
                    "cashier_id",
                    models.ForeignKey(
                        db_column="cashier_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.cashier",
                    ),
                ),
                (
                    "loyalty_card_id",
                    models.ForeignKey(
                        db_column="loyalty_card_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.loyaltycard",
                    ),
                ),
                (
                    "shift_id",
                    models.ForeignKey(
                        db_column="shift_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чеки",
                "verbose_name_plural": "Чеки",
                "db_table": "receipts",
            },
        ),
        migrations.CreateModel(
            name="ProductsForPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(max_length=100, verbose_name="Наименование"),
                ),
                ("count", models.IntegerField(verbose_name="Цена 1 позиции")),
                ("unit", models.IntegerField(verbose_name="Количество в 1 позиции")),
                ("url", models.CharField(max_length=100, verbose_name="URL")),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.categoryproducts",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты",
                "verbose_name_plural": "Заказ продуктов",
                "db_table": "products_for_purchase",
            },
        ),
        migrations.CreateModel(
            name="PositionReceipt",
            fields=[
                ("id_position", models.BigAutoField(primary_key=True, serialize=False)),
                ("product", models.TextField()),
                ("count", models.IntegerField()),
                ("price", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("percent_bonus", models.IntegerField()),
                ("barcode", models.BigIntegerField()),
                (
                    "id_product",
                    models.ForeignKey(
                        db_column="id_product",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.product",
                    ),
                ),
                (
                    "id_receipt",
                    models.ForeignKey(
                        db_column="id_receipt",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чек по позициям",
                "verbose_name_plural": "Чек по позициям",
                "db_table": "position_receipt",
            },
        ),
        migrations.CreateModel(
            name="MonthPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("availability", models.JSONField(default=dict)),
                ("priority_points", models.JSONField(default=list)),
                ("blocked_points", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_prefs",
                        to="loyalty_backend.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пожелания на месяц",
                "verbose_name_plural": "Пожелания на месяц",
                "db_table": "month_preference",
            },
        ),
        migrations.CreateModel(
            name="MilkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "milk",
                    models.ForeignKey(
                        db_column="milk",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loyalty_backend.milk",
                        to_field="name_product",
                        verbose_name="Молоко",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="loyalty_backend.milkorder",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
                "db_table": "milk_order_item",
            },
        ),
        migrations.CreateModel(
            name="GoogleSheetSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sheet_row_id", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty_backend.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                ("point_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("old_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_history",
                        to="loyalty_backend.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "История расходов",
                "verbose_name_plural": "Истории расходов",
                "db_table": "expense_history",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        db_column="cashier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="loyalty_backend.cashier",
                        to_field="short_name_point",
                        verbose_name="Кофейня",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="loyalty_backend.expensecategory",
                        to_field="name",
                        verbose_name="Статья расходов",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loyalty_backend.employee",
                        to_field="full_name",
                        verbose_name="Кто добавил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
                "db_table": "expense_per_month",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("user_id", "cashier_id", "date_shift"), name="shift_id_cashier"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthpreference",
            unique_together={("employee", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="googlesheetsalary",
            unique_together={("employee", "week_start")},
        ),
        migrations.AlterUniqueTogether(
            name="expense",
            unique_together={("cashier", "category", "created_at")},
        ),
    ]
